import { Inter } from "next/font/google";
import "./globals.css";
import Section from "@/components/atoms/Section";
import Navbar from "@/components/molecules/Navbar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.variable}`}>
        <Section>
          <Navbar />
          {children}
        </Section>
      </body>
    </html>
  );
}
